apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello
          image: hozefabata/hello-app:latest
          ports:
            - containerPort: 8383
          readinessProbe:
            httpGet:
              path: /
              port: 8383
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8383
            initialDelaySeconds: 10
            periodSeconds: 20
